LibraryManagement/LibraryManagement/Controllers/CheckStatusController.cs
using LibraryManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.Controllers
{
    public class CheckStatusController : Controller
    {
       
        dbcontext db = new dbcontext();
        // GET: CheckStatus
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string id)
        {
            return View(db.IssueBooks.Where(x => x.IdCard == id).ToList());
        }
        public ActionResult check()
        {
            return View();
        }
        [HttpPost]
        public ActionResult check(string id)
        {

            Membership mm = db.Memberships.FirstOrDefault(x => x.Idnumber == id);
            if(mm!=null)
            {
                Session["id"] = mm.Mid;
                return View(db.IssueBooks.Where(x => x.IdCard == id).ToList());
            }
            else
            {
                TempData["Danger"] = "Card Number Not Found";
                return View();
            }
            
        }
        public ActionResult Add(int id)
        {
            int ids = Convert.ToInt32(id);
            db.Configuration.ProxyCreationEnabled = false;
            Membership member = db.Memberships.Find(id);

          

            return PartialView("~/Views/CheckStatus/AddBook.cshtml", member);
        }
        [HttpPost]
        public ActionResult CreateBook([Bind(Include ="Mid,IdCard,Bid,IssueDate,LastDate,Fine,Status")] IssueBook books,int bookid)
        {
            
            if (ModelState.IsValid)
            {
                Books book = db.Books.Find(bookid);
                Setting ss = db.Settings.First();
                if (book.BookCopies > ss.BookAlert)
                {
                    books.Bid = bookid;
                    books.Status = "Issue";
                    books.fine = 0;
                    db.IssueBooks.Add(books);
                    db.SaveChanges();
                    #region Update Book Quantity

                    book.BookCopies = book.BookCopies - 1;

                    db.Entry(book).State = EntityState.Modified;
                    db.SaveChangesAsync();
                    #endregion
                    TempData["Success"] = "Issue Book Successfully";
                }
                else
                {
                    TempData["Success"] = "Quantity Not Sufficient";
                    return RedirectToAction("add",new { id=books.Mid});
                }

                
            }
            return RedirectToAction("add", new { id = books.Mid }); 
        }
        public ActionResult IssueList()
        {
            return View(db.IssueBooks.ToList());
        }
        public ActionResult ReturnBook(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            IssueBook books = new IssueBook();
            Setting ss = db.Settings.FirstOrDefault();
            books = db.IssueBooks.Where(x => x.Sid == id).First();
            DateTime todaydate = System.DateTime.Now;
            var diff = (todaydate.Day- books.LastDate.Day);
            if (Convert.ToInt32(diff) < 0)
            {
                books.returnfine = 0;
            }
            else
            {
                books.returnfine = ss.Fine * Convert.ToInt32(diff);
            }

            return PartialView("~/Views/CheckStatus/ReturnBook.cshtml", books);
        }
        public ActionResult Return([Bind(Include = "Sid,Mid,IdCard,Bid,IssueDate,LastDate,ReturnDate,fine,Status,returnfine")] IssueBook issue)
        {
            if (ModelState.IsValid)
            {
                if (issue.returnfine == issue.fine)
                {
                    issue.Status = "Return";
                    db.Entry(issue).State = EntityState.Modified;
                    db.SaveChanges();

                    if (issue.ReturnDate == null)
                    {
                        Books bb = db.Books.Find(issue.Bid);
                        bb.BookCopies = bb.BookCopies + 1;
                        db.Entry(bb).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["Success"] = "Update Records Successfully";

                    }
                    else
                    {
                        TempData["Success"] = "Return Book Successfully";

                    }
                }
                else
                {
                    TempData["Success"] = "Deposit Fine";
                }
                
                
                return RedirectToAction("check");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            IssueBook books = new IssueBook();
            Setting ss = db.Settings.FirstOrDefault();
            books = db.IssueBooks.Where(x => x.Sid == id).First();
            DateTime todaydate = System.DateTime.Now;
            var diff = (todaydate.Day - books.LastDate.Day);
            books.fine = ss.Fine * Convert.ToInt32(diff);

            return PartialView("~/Views/CheckStatus/ReturnBook.cshtml", books);

        }
     }
}

LibraryManagement/LibraryManagement/Views/CheckStatus/AddBook.cshtml
@model LibraryManagement.Models.Membership
@using LibraryManagement.Models
@{ 
    dbcontext db = new dbcontext();
    IEnumerable<Books> book = db.Books.ToList();
    IssueBook books = new IssueBook();
    books.Mid = Model.Mid;
    books.IdCard = Model.Idnumber;
    Helper help = new Helper();
}

@using (Html.BeginForm("CreateBook","CheckStatus"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Member Name</label>
            @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
          <label>Book Name / Book No.</label>
           <select class="normalDropDown form-control" name="bookid">
               @foreach (var item in book)
               {
                    <option value="@item.boid">@item.ISBN - @item.Name</option>
               }
           </select>
        </div>

        <div class="form-group">
            <label>Issue Date</label>
            @Html.EditorFor(Model => books.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(Model=>books.Mid)
            @Html.HiddenFor(Model => books.IdCard)
        </div>
        <div class="form-group">
            <label>Last Date</label>
            @Html.EditorFor(Model => books.LastDate, new { htmlAttributes = new { @class = "form-control" } })
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-space btn-primary" />
            </div>
        </div>
    </div>
}

<span>Hello</span>

LibraryManagement/LibraryManagement/Views/CheckStatus/Index.cshtml
@model IEnumerator<LibraryManagement.Models.Membership>
@using LibraryManagement.Models

@{
    dbcontext db = new dbcontext();
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("Index","CheckStatus"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Batch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Enter Library CardNumber</label>
            @*@Html.EditorFor(model => model.Idnumber, new { htmlAttributes = new { @class = "form-control" } })*@


        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-space btn-primary" />
                <a href="javascript:void(0);" onclick="AddBook(1)">Add Book</a>
            </div>
        </div>
    </div>
}
<table class="table table-striped table-hover table-fw-widget" id="table5">
    <thead>
        <tr>
            <th>
                Holder Name
            </th>

            <th>
                Book Name
            </th>
            <th>
                Issue Date
            </th>
            <th>
                Due Date
            </th>
            <th>
                Return Date
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @db.Memberships.Find(item.Mid).StudentName
                </td>
                <td>
                    @db.Books.Find(item.Bid).Name
                </td>

                <td>
                    @Convert.ToDateTime(item.IssueDate).ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Convert.ToDateTime(item.LastDate).ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Convert.ToDateTime(item.ReturnDate).ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class="badge badge-primary">Edit</a> |
                    <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class="badge badge-danger">Return Book</a>
                </td>
            </tr>
        }
    </tbody>
</table>

    


<div class="modal fade colored-header colored-header-primary" id="form-bp1" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-colored">
                <h3 class="modal-title">Update Follow Up</h3>
                <button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close">       </span></button>
            </div>
            <div class="modal-body" id="myModalBodyDiv1">

            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary md-close" type="button" data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary md-close" type="button" data-dismiss="modal">Proceed</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-1.10.2.js"
        integrity="sha256-it5nQKHTz+34HijZJQkpNBIHsjpV8b6QzMJs9tmOBSo="
        crossorigin="anonymous"></script>
@section scripts
{
    <script>


    var AddBook=function(Member){
        debugger;
        var url = "/CheckStatus/Add?id=" + Member;
       // var url = "/Model/EmployeePartial";
        $("#myModalBodyDiv1").load(url, function () {

            $("#form-bp1").modal("show");

        })

    }
    </script>
<script>


    var BookHistory=function(Member){
        debugger;
        var url = "/CheckStatus/History?id=" + Member;
       // var url = "/Model/EmployeePartial";
        $("#myModalBodyDiv1").load(url, function () {

            $('#divid').innerHTML = data;

        })

    }
</script>
}

LibraryManagement/LibraryManagement/Views/CheckStatus/IssueHistoryByCard.cshtml
<table class="table table-striped table-hover table-fw-widget" id="table3">
    <thead>
        <tr>
            <th>
                Holder Name
            </th>

            <th>
                Book Name
            </th>
            <th>
                Issue Date
            </th>
            <th>
                Due Date
            </th>
            <th>
                Return Date
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @db.Memberships.Find(item.Mid).StudentName
                </td>
                <td>
                    @db.Books.Find(item.Bid).Name
                </td>

                <td>
                    @Convert.ToDateTime(item.IssueDate).ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Convert.ToDateTime(item.LastDate).ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Convert.ToDateTime(item.ReturnDate).ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class="badge badge-primary">Edit</a> |
                    <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class="badge badge-danger">Return Book</a>
                </td>
            </tr>
        }
    </tbody>
</table>

LibraryManagement/LibraryManagement/Views/CheckStatus/IssueList.cshtml
@model IEnumerable<LibraryManagement.Models.IssueBook>
@using LibraryManagement.Models
@{
    ViewBag.Title = "IssueList";
    Layout = "~/Views/Shared/Layout.cshtml";
    dbcontext db = new dbcontext();
}

<h2>IssueList</h2>

<hr />
<table class="table table-striped table-hover table-fw-widget" id="table3">
 <thead>
    <tr>
        <th>
            Holder Name
        </th>
     
        <th>
            Book Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssueDate)
        </th>
        <th>
           Due Date
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>
	 </thead>
	 <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @db.Memberships.Find(item.Mid).StudentName
        </td>
        <td>
            @db.Books.Find(item.Bid).Name
        </td>
       
        <td>
            @Convert.ToDateTime(item.IssueDate).ToString("dd/MM/yyyy")
        </td>
        <td>
            @Convert.ToDateTime(item.LastDate).ToString("dd/MM/yyyy")
        </td>
        <td>
            @Convert.ToDateTime(item.ReturnDate).ToString("dd/MM/yyyy")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class="badge badge-primary" >Edit</a> |
            <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class= "badge badge-danger" >Return Book</a>
        </td>
    </tr>
}
</tbody>
</table>
<div class="modal fade colored-header colored-header-primary" id="form-bp1" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-colored">
                <h3 class="modal-title">Return Book</h3>
                <button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close">       </span></button>
            </div>
            <div class="modal-body" id="myModalBodyDiv1">

            </div>
            
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.js"
        integrity="sha256-it5nQKHTz+34HijZJQkpNBIHsjpV8b6QzMJs9tmOBSo="
        crossorigin="anonymous"></script>
@section scripts
{
    <script>


    var ReturnBook=function(Bookid){
        debugger;
        var url = "/CheckStatus/ReturnBook?id=" + Bookid;
       // var url = "/Model/EmployeePartial";
        $("#myModalBodyDiv1").load(url, function () {

            $("#form-bp1").modal("show");

        })

    }
    </script>
}

LibraryManagement/LibraryManagement/Views/CheckStatus/ReturnBook.cshtml
@model LibraryManagement.Models.IssueBook
@using LibraryManagement.Models
@{
    dbcontext db = new dbcontext();
    


}

@using (Html.BeginForm("Return", "CheckStatus"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model=>model.Mid)
    @Html.HiddenFor(model => model.Bid)
    @Html.HiddenFor(model => model.Status)
    @Html.HiddenFor(model => model.IdCard)
    @Html.HiddenFor(model => model.Sid)
    @Html.HiddenFor(model => model.IssueDate)
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="form-group col-md-6">
                <label>Student Name</label>
                <input type="text" value="@db.Memberships.Find(Model.Mid).StudentName" class="form-control" />
            </div>
            <div class="form-group col-md-6">
                <label>Book</label>
                <input type="text" value="@db.Books.Find(Model.Bid).Name" class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label>Due Date</label>
                @Html.EditorFor(model => model.LastDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-md-6">
                <label>Late Fine</label>
                @Html.EditorFor(model => model.returnfine, new { htmlAttributes = new { @class = "form-control" } })


            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label>Return Date</label>
                @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label>Deposit Fine</label>
                @Html.EditorFor(Model => Model.fine, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-space btn-primary" />
                </div>
            </div>
        </div>
}

LibraryManagement/LibraryManagement/Views/CheckStatus/check.cshtml
@model IEnumerable<LibraryManagement.Models.IssueBook>
@using LibraryManagement.Models
 @{
     ViewBag.Title = "check";
     Layout = "~/Views/Shared/Layout.cshtml";
     dbcontext db = new dbcontext();
}



    @using (Html.BeginForm("check", "CheckStatus"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Enter Library Card Number</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label>Enter Library CardNumber</label>
                @*@Html.EditorFor(model => model.Idnumber, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="text" name="id" class="form-control" />

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-space btn-primary" />

                </div>
            </div>
        </div>
    }
    @if (Model != null)
    {
        int a = Convert.ToInt32(Session["id"]);
        <a href="javascript:void(0);" onclick="AddBook(@a)" class="btn btn-danger">Add Issue Book</a>
        <table class="table table-striped table-hover table-fw-widget" id="table5">
            <thead>
                <tr>
                    <th>
                        Student Name
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IdCard)
                    </th>
                    <th>
                       Book Name
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IssueDate)
                    </th>
                    <th>
                        Due Date
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ReturnDate)
                    </th>
                   
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @db.Memberships.Find(item.Mid).StudentName
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.IdCard)
                        </td>
                        <td>
                            @db.Books.Find(item.Bid).Name
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IssueDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReturnDate)
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Sid }, new { @class = " badge badge-primary" }) |

                            <a href="javascript:void(0);" onclick="ReturnBook(@item.Sid)" class="badge badge-danger">Return Book</a> |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Sid }, new { @class = " badge badge-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }



    <div class="modal fade colored-header colored-header-primary" id="form-bp1" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-colored">
                    <h3 class="modal-title">Issue Book</h3>
                    <button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close">       </span></button>
                </div>
                <div class="modal-body" id="myModalBodyDiv1">

                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary md-close" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-primary md-close" type="button" data-dismiss="modal">Proceed</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-1.10.2.js"
            integrity="sha256-it5nQKHTz+34HijZJQkpNBIHsjpV8b6QzMJs9tmOBSo="
            crossorigin="anonymous"></script>
    @section scripts
{
        <script>


            var AddBook = function (Member) {
                debugger;
                var url = "/CheckStatus/Add?id=" + Member;
                // var url = "/Model/EmployeePartial";
                $("#myModalBodyDiv1").load(url, function () {

                    $("#form-bp1").modal("show");

                })

            }
        </script>

        <script>


            var ReturnBook = function (Bookid) {
                debugger;
                var url = "/CheckStatus/ReturnBook?id=" + Bookid;
                // var url = "/Model/EmployeePartial";
                $("#myModalBodyDiv1").load(url, function () {

                    $("#form-bp1").modal("show");

                })

            }
        </script>
    }